# Copyright 2020 Donghyun Alex Kim
# Based on https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml

site_name: Donghyun Kim
nav:
  - Home: index.md
  - Projects:
    - SUAS Design Team: projects/suas.md
    - 4D Avionic Systems: projects/4davsys.md
    - Master's Thesis: projects/thesis.md
site_description: Portfolio of my engineering work
site_author: Donghyun Kim
site_url: https://0b10010010.github.io/portfolio/

repo_name: 0b10010010/portfolio
repo_url: https://github.com/0b10010010/portfolio

theme:
  name: material
  favicon: img/cpu.svg
  logo: img/cpu-fill.svg

copyright: Copyright &copy; 2020 Donghyun Kim

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
